### ISSUE TITLE
Удаление из членов организации и участников в репо Я.Практикума

### ISSUE THREAD

**Issue by ablohin** [vlad-iv/java-filmorate#4]
Влад, привет. Не смог найти твоих контактов, поэтому пришлось написать сюда.
Я работал в Я.Практикуме в прошлом году и уволился, но меня не полностью удалили из всех сервисов.
На данный момент до сих пор приходят уведомления от github, поэтому удали меня пожалуйста из **praktikum-java**: https://github.com/praktikum-java.
Инструкция по удалению из списка участников и списка членов организации:
https://docs.github.com/ru/github-ae@latest/admin/user-management/managing-organizations-in-your-enterprise/removing-users-from-teams-and-organizations

**Comment by vlad-iv** [comment]
Удалил
